apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: cassandra
    env: dev
  name: sc-node-data
provisioner: kubernetes.io/aws-ebs
parameters:
  # volume-types: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
  # type: io1 # requires at least 4 GB
  type: io1
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: cassandra
    env: dev
  name: sc-node-log
provisioner: kubernetes.io/aws-ebs
parameters:
  # volume-types: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
  type: gp2
  iopsPerGB: "100"
  fsType: ext4
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer